const { nanoid } = require("nanoid");

const tweetsData = [
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: ["https://picsum.photos/id/237/200/200"],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: ["https://picsum.photos/id/237/200/200"],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: ["https://picsum.photos/id/237/200/200"],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: ["https://picsum.photos/id/237/200/200"],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: ["https://picsum.photos/id/237/200/200"],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: ["https://picsum.photos/id/237/200/200"],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: [],
    likes: [],
    retweets: [],
  },
  {
    _id: nanoid(12),
    createdAt: new Date().toDateString(),
    updatedAt: new Date().toDateString(),
    content: "Random tweet",
    user: "",
    imageSrc: ["https://picsum.photos/id/237/200/200"],
    likes: [],
    retweets: [],
  },
];

module.exports = tweetsData;
